name: ZMediumToMarkdown
on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 15 * *" # Runs at 01:10 (UTC) on the 15th of every month.
    # Schedule to automatically sync at specified intervals
    # Reference: https://crontab.guru/

permissions:
  contents: write
  
jobs:
  ZMediumToMarkdown:
    runs-on: ubuntu-latest
    steps:
    - name: ZMediumToMarkdown Automatic Bot
      uses: ZhgChgLi/ZMediumToMarkdown@main
      with:
        command: "--cookie_uid ${{ secrets.MEDIUM_COOKIE_UID }} --cookie_sid ${{ secrets.MEDIUM_COOKIE_SID }} -j jackycsie"
        # Replace 'zhgchgli_test' with your Medium username
        # For example, https://medium.com/@zhgchgli -> zhgchgli
        # Reference: https://github.com/ZhgChgLi/ZMediumToMarkdown?tab=readme-ov-file#usage
